spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    show-sql: true

server:
  servlet:
    context-path: /api/

jwt:
  secret:
    key: 7639792442264528482B4D6251655468576D5A7134743777217A25432A462D4A